# Generated by Django 2.2.1 on 2019-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeatBooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='bookings_booked',
        ),
        migrations.AddField(
            model_name='userbooking',
            name='turned_up_status',
            field=models.CharField(blank=True, choices=[('t', 'Turned Up'), ('n', 'None')], default='n', help_text='Turned up status', max_length=1),
        ),
    ]
