# Generated by Django 2.2.1 on 2019-08-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeatBooking', '0002_auto_20190815_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='employeeId',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='userbooking',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
