# Generated by Django 2.2.1 on 2019-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('a', 'Admin'), ('e', 'Employee'), ('d', 'Driver')], default='e', help_text='Select type of User', max_length=1)),
                ('employeeId', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
